### ISSUE TITLE
Lock app not working in High Sierra?

### ISSUE THREAD

**Issue by thirstybear** [siong1987/shortcuts#16]
I've just updated to macOS 10.13.1 High Sierra, and the Lock app starts and exits without locking the screen (sorry, haven't tested anything else yet - lock is the one I use most of the time).

Cheers.

Chris

**Comment by siong1987** [comment]
Check out the new [1.0.1](https://github.com/siong1987/shortcuts/releases/tag/1.0.1) release. The Lock.app should be fixed.

**Comment by thirstybear** [comment]
Thanks. I can confirm the update fixes the issue.
Cheers!
