### ISSUE TITLE
Shutdown command without saving last session

### ISSUE THREAD

**Issue by xyNNN** [siong1987/shortcuts#8]
Currently when i use the shutdown application it will reopen all my applications which are opened before i shutdown my system. It is possible to configure these shortcut command to disable this feature?

**Comment by xyNNN** [comment]
How is it going with this issue? ;)

**Comment by siong1987** [comment]
@xyNNN sorry.  not really have time to work on this :(

**Comment by xyNNN** [comment]
Okay, no problem. Then let's close this issue and we came back to this when you've time again ;)
